import { useState } from "react";
import { motion } from "framer-motion";

// FAQ data
const faqs = [
  {
    question: "How does Genixor build websites so fast?",
    answer:
      "Genixor uses AI to instantly generate layouts, content, and structure based on your idea — reducing hours of work into seconds.",
  },
  {
    question: "Can I customize the generated website?",
    answer:
      "Yes. You can fully edit layouts, colors, fonts, and content while AI maintains visual consistency across pages.",
  },
  {
    question: "Is the website mobile responsive?",
    answer:
      "Absolutely. Every website generated by Genixor is fully responsive and optimized for all screen sizes.",
  },
  {
    question: "Can I deploy my website instantly?",
    answer:
      "Yes. With one click, you can publish your website with built-in performance and SEO optimization.",
  },
  {
    question: "Do I need coding knowledge?",
    answer:
      "No coding required. Genixor is designed for founders, creators, and teams who want to launch quickly without technical barriers.",
  },
];

// Animation settings
const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.12 },
  },
};
const item = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { duration: 0.5 } },
};

const FAQSection = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  // Toggle FAQ function
  const toggleFAQ = (index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <section
      id="faq"
      className="bg-black py-20 px-4  
      bg-[radial-gradient(rgba(166,255,93,0.15)_1.5px,transparent_0)]
      bg-size-[20px_20px]
      bg-position-[-1px_-1px] bg-fixed"
    >
      <motion.div
        initial="hidden"
        whileInView="show"
        viewport={{ once: true, margin: "-100px" }}
        variants={container}
        className="max-w-3xl mx-auto text-center"
      >
        {/* Heading */}
        <motion.h2 variants={item} className="text-3xl md:text-4xl text-white">
          Got Questions about{" "}
          <span className="text-[#A6FF5D] italic">Genixor?</span>
        </motion.h2>

        {/* Description */}
        <motion.p variants={item} className="text-white/60 text-sm mt-3 mb-10">
          Everything you need to know before building your AI-powered website.
        </motion.p>

        {/* FAQ List */}
        <motion.div variants={container} className="space-y-4 text-left">
          {faqs.map((faq, index) => {
            const isOpen = activeIndex === index;

            return (
              <motion.div
                key={index}
                variants={item}
                whileHover={{ scale: 1.01 }}
                className="border border-neutral-800 rounded-2xl bg-neutral-900/70 backdrop-blur transition hover:border-[#A6FF5D]/40"
              >
                {/* Question */}
                <button
                  onClick={() => toggleFAQ(index)}
                  className="w-full flex items-center justify-between px-6 py-5 text-left"
                >
                  <span className="text-white/90">{faq.question}</span>

                  <span
                    className={`transition-transform duration-300 text-[#A6FF5D] ${
                      isOpen ? "rotate-180" : ""
                    }`}
                  >
                    <svg
                      className="w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </span>
                </button>

                {/* Answer */}
                <motion.div
                  initial={false}
                  animate={{
                    height: isOpen ? "auto" : 0,
                    opacity: isOpen ? 1 : 0,
                  }}
                  transition={{ duration: 0.3 }}
                  className="px-6 overflow-hidden"
                >
                  <p className="text-white/60 text-sm pb-6">{faq.answer}</p>
                </motion.div>
              </motion.div>
            );
          })}
        </motion.div>
      </motion.div>
    </section>
  );
};

export default FAQSection;
