import { useState } from "react";
import { motion } from "framer-motion";

// FAQ data
const faqs = [
  {
    question: "How does the Genixor AI engine build production-ready websites in seconds?",
    answer:
      "Genixor utilizes next-generation deep learning models trained on premium design systems to instantly generate clean HTML structure, custom Tailwind CSS layouts, and engaging copy based on your description. It replaces days of wireframing, designing, and coding with an automated pipeline that completes in under 10 seconds.",
  },
  {
    question: "To what extent can I customize and edit the websites generated by the AI?",
    answer:
      "You have complete creative control. Using our visual interactive editor, you can click on any element to modify text, swap out fonts, tweak margins, customize colors, and adjust layouts. The underlying AI engine handles design consistency in the background, ensuring your changes adhere to premium aesthetic rules.",
  },
  {
    question: "Are the generated websites fully optimized and responsive across all device breakpoints?",
    answer:
      "Absolutely. Genixor uses a mobile-first fluid layout design system. Every website generated automatically shifts and scale-adjusts across phones, tablets, laptops, and ultra-wide desktop monitors, guaranteeing high performance and pixel-perfect rendering on any screen size.",
  },
  {
    question: "What hosting and deployment options are available when my website is ready?",
    answer:
      "Every project comes with free, instant global edge network hosting. With a single click, your site is built for production, optimized for fast loading speeds, pre-configured with essential SEO metadata, and deployed to a secure HTTPS URL. You can also export the production-ready code directly.",
  },
  {
    question: "Do I need any prior coding, development, or design experience to use Genixor?",
    answer:
      "No coding or design skills are required at all. Genixor is built specifically to bridge the gap between creative ideas and live web apps. Whether you are a startup founder launching a landing page, a creator building a portfolio, or a team drafting a prototype, you can manage the entire cycle visually.",
  },
];

// Animation settings
const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.12 },
  },
};
const item = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { duration: 0.5 } },
};



const slideRightItem = {
  hidden: { opacity: 0, x: 70 },
  show: {
    opacity: 1,
    x: 0,
    transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] },
  },
} as const;

const FAQSection = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  // Toggle FAQ function
  const toggleFAQ = (index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <section
      id="faq"
      className="bg-black py-20 px-4"
    >
      <motion.div
        initial="hidden"
        whileInView="show"
        viewport={{ once: true, margin: "-100px" }}
        variants={container}
        className="max-w-5xl mx-auto flex flex-col items-end w-full"
      >
        {/* Heading */}
        <motion.h2 variants={slideRightItem} className="text-4xl md:text-5xl text-white tracking-tight text-center md:text-right font-light w-full">
          Got Questions about{" "}
          <span className="text-[#A6FF5D] italic">Genixor?</span>
        </motion.h2>

        {/* FAQ List */}
        <motion.div variants={container} className="space-y-4 text-left mt-10 w-full">
          {faqs.map((faq, index) => {
            const isOpen = activeIndex === index;

            return (
              <motion.div
                key={index}
                variants={item}
                whileHover={{ scale: 1.01 }}
                className="border border-neutral-800 rounded-2xl bg-neutral-900/70 backdrop-blur transition hover:border-[#A6FF5D]/40"
              >
                {/* Question */}
                <button
                  onClick={() => toggleFAQ(index)}
                  className="w-full flex items-center justify-between px-6 py-5 text-left"
                >
                  <span className="text-white/90">{faq.question}</span>

                  <span
                    className={`transition-transform duration-300 text-[#A6FF5D] ${
                      isOpen ? "rotate-180" : ""
                    }`}
                  >
                    <svg
                      className="w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </span>
                </button>

                {/* Answer */}
                <motion.div
                  initial={false}
                  animate={{
                    height: isOpen ? "auto" : 0,
                    opacity: isOpen ? 1 : 0,
                  }}
                  transition={{ duration: 0.3 }}
                  className="px-6 overflow-hidden"
                >
                  <p className="text-white/60 text-sm pb-6">{faq.answer}</p>
                </motion.div>
              </motion.div>
            );
          })}
        </motion.div>
      </motion.div>
    </section>
  );
};

export default FAQSection;
