import { useState } from "react";

// FAQ data
const faqs = [
  {
    question: "How does Genixor build websites so fast?",
    answer:
      "Genixor uses AI to instantly generate layouts, content, and structure based on your idea — reducing hours of work into seconds.",
  },
  {
    question: "Can I customize the generated website?",
    answer:
      "Yes. You can fully edit layouts, colors, fonts, and content while AI maintains visual consistency across pages.",
  },
  {
    question: "Is the website mobile responsive?",
    answer:
      "Absolutely. Every website generated by Genixor is fully responsive and optimized for all screen sizes.",
  },
  {
    question: "Can I deploy my website instantly?",
    answer:
      "Yes. With one click, you can publish your website with built-in performance and SEO optimization.",
  },
  {
    question: "Do I need coding knowledge?",
    answer:
      "No coding required. Genixor is designed for founders, creators, and teams who want to launch quickly without technical barriers.",
  },
];

const FAQSection = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <section
      id="faq"
      className="bg-black py-20 px-4  bg-[radial-gradient(rgba(166,255,93,0.15)_1.5px,transparent_0)]
        bg-size-[20px_20px]
        bg-position-[-1px_-1px] bg-fixed"
    >
      <div className="max-w-3xl mx-auto text-center">
        {/* Heading */}
        <h2 className="text-3xl md:text-4xl text-white">
          Got Questions about{" "}
          <span className="text-[#A6FF5D] italic">Genixor?</span>
        </h2>

        {/* Description */}
        <p className="text-white/60 text-sm mt-3 mb-10">
          Everything you need to know before building your AI-powered website.
        </p>

        {/* FAQ List */}
        <div className="space-y-4 text-left">
          {faqs.map((faq, index) => {
            const isOpen = activeIndex === index;

            return (
              <div
                key={index}
                className="border border-neutral-800 rounded-2xl bg-neutral-900/70 backdrop-blur transition hover:border-[#A6FF5D]/40"
              >
                {/* Question */}
                <button
                  onClick={() => toggleFAQ(index)}
                  className="w-full flex items-center justify-between px-6 py-5 text-left"
                >
                  <span className="text-white/90 ">{faq.question}</span>

                  <span
                    className={`transition-transform duration-300 text-[#A6FF5D] ${
                      isOpen ? "rotate-180" : ""
                    }`}
                  >
                    <svg
                      className="w-4 h-4 text-[#A6FF5D]"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </span>
                </button>

                {/* Answer */}
                <div
                  className={`px-6 overflow-hidden transition-all duration-300 ${
                    isOpen ? "max-h-40 pb-6" : "max-h-0"
                  }`}
                >
                  <p className="text-white/60 text-sm">{faq.answer}</p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
